### ISSUE TITLE
segfault on MacOS SODA 1.1.1.1

### ISSUE THREAD

**Issue by nendonerd** [biemster/gasr#10]
In your commit message, gasr.py supports SODA 1.1.0.1, while my chrome is using SODA 1.1.1.1.
But still I followed ur instructions and patched `libsoda.so` on MacOS, and the whole thing was not working as expected.

The error occurs at calling `CreateExtendedSodaAsync(self.config)`
Ghidra shows that `CreateExtendedSodaAsync` no longer takes any params, and hands over the initialization job to `__ZN6speech4soda24ExtendedSodaAsyncWrapper6CreateE18ExtendedSodaConfig`, which is a mangled non exported funtion.

<img width="1920" src="https://user-images.githubusercontent.com/14371029/169480191-af5ac475-c80d-45da-8b8d-e983b42687e6.png">
<img width="1920" src="https://user-images.githubusercontent.com/14371029/169480272-a9656d6d-e956-4d93-afd3-416e66464f2b.png">

The address of this function is `0x00004414`. I try to call this function by address in python, but i could not make it work. 

Then I try to hook it with frida to find out what's going on:
```js
// find the pid who's using SODA by calling `lsof libsoda.so`
// frida -l ./hook.js -p pid
// then refresh a chrome page with live caption enabled

Interceptor.attach(Module.findBaseAddress('libsoda.so').add(0x00004414), {
    onEnter: function(args) {
        console.log('--------')
        
        console.log(0, args[0]) // 0x16f33e2f0  ?
        console.log(1, args[1])  // 0x16f33e378  ?
        console.log(2, args[2]) // 0xac44      sample rate: 44100
        console.log(3, args[3]) // 0x1         channel: 1
        console.log(4, args[4]) // 0xfffffffffff990b0  api_key?
        console.log(5, args[5]) // 0x10        bitdepth 16
        console.log(6, args[6]) // 0x62        ?
        // ...???
    }
})
```
There seems to be a huge amount of arguments, probably from some struct.

So I have a few curious questions:
1. Do you plan to update gasr.py to support latest version of SODA ?
2. How to find and download previous versions of SODA ?
3. How to call a non exported function in python ?
4. How did you find out the params of `CreateExtendedSodaAsync` and the fields of `SodaConfig`? It seems to be related to protobuf, where and how did you find that protobuf ?
5. Which function should I hook to get the output text from SODA ?

**Comment by biemster** [comment]
Nice RE skills! I want to keep up with current versions of SODA, so this needs to be working properly. That said, I don't have an osx or windows box to test on so all work is done on linux, and I just hope the other platforms then work as well. Did you by any chance see issue #4 and could it be related to that? I did not work on 1.1.1.1 yet, so it is very possible that the API chanced.
Although that AsyncWrapper function has always been there, this is possibly just Ghidra struggling a bit with decompiling.
To answer your questions:
1. yes
2. I don't know a way to download previous versions of SODA except if you saved the exact link given by the updater service when it was the latest, but I have some old versions lying around (almost exclusively linux though..)
3. I doubt that you can call non exported functions in python, but I'm also fairly certain you really don't need to.
4. The params of the SODA functions I gleaned from the implementation, and the protobuf, in the chromium source: https://github.com/chromium/chromium/tree/main/chrome/services/speech/soda
5. The SODA library expects a callback in the config, that's the one that is called when it wants to give output.

**Comment by biemster** [comment]
I have a python script that fetches the urls, but as long as I am monitoring it (about 2 years) I never had the need to use an old version so I doubt that this incremental update is going to disable me from getting it to work. (Also there don't seem to be any repurposing of libsoda in any other projects so I doubt the google speech team will put effort in obfuscating it more)

The updater indeed always returns the latest version of the url.

**Comment by nendonerd** [comment]
nice unzip trick !

**Comment by biemster** [comment]
Now I think of it a bit harder, it's very unlikely that the API changed for 1.1.1.1 since I did not see any commit like that in the chromium repository (or in the soda client code there). Since it will take a while before I get to decompiling again, @nendonerd could you show the error message you are getting, and describe roughly (not too exact, let others have some fun too) what you patched in the lib?

**Comment by nendonerd** [comment]
```
nendo@NendoMBP gasr % python3 gasr.py < sample.wav
W0000 00:00:1653109171.479487       1 soda_async_impl.cc:334] Creating soda_impl.
W0000 00:00:1653109171.550838       1 terse_processor.cc:342] TISID disabled.
W0000 00:00:1653109171.556616       2 portable_intended_query_stream.cc:236] Exiting due to stream cancellation.
W0000 00:00:1653109171.556893       1 decoder_endpointer_stream.cc:72] Acoustic ep reader thread cancelled.
W0000 00:00:1653109171.557399       1 soda_async_impl.cc:561] SODA session starting (require_hotword:0, hotword_timeout_in_millis:0, trigger_type:TRIGGER_TYPE_UNSPECIFIED, hybrid_asr_config.mode:MODE_DEFAULT)
W0000 00:00:1653109171.557686       1 soda_async_impl.cc:612] Nice value changed from <Unknown> to <Unknown>. Restarting SODA thread.
zsh: segmentation fault  python3 gasr.py < sample.wav
```
this is using an uncrack soda 1.1.1.1 on macos

**Comment by nendonerd** [comment]
the crack i did was located at:
- 00004ad8 `_CreateExtendedSodaAsync()`
- 00004414 `speech::soda::ExtendedSodaAsyncWrapper::Create(ExtendedSodaConfig)`
- 000044f0 `speech::soda::ExtendedSodaAsyncWrapper::CreateWithSoda(ExtendedSodaConfig, std::__1::unique_ptr<speech::soda::SodaAsyncBase, std::__1::default_delete<speech::soda::SodaAsyncBase>>)`
- 00003ae8 `speech::soda::ExtendedSodaAsyncWrapper::ExtendedSodaAsyncWrapper(ExtendedSodaConfig,speech::soda::chrome::ExtendedSodaConfigMsg, std::__1::unique_ptr<speech::soda::SodaAsyncBase,std::__1::default_delete<speech::soda::SodaAsyncBase>>)`
<img width="1920" alt="Screen Shot 2022-05-21 at 13 09 19 (3)" src="https://user-images.githubusercontent.com/14371029/169636436-23597e2c-5a27-4626-a893-2fa530db9cda.png">
there're 4 consecutive verify functions, which is 4 (bl + cbz). I patch these (bl + cbz) with nop `1F 20 03 D5` (little endian in aarch64). After patching, running above command throws the same error msg

**Comment by biemster** [comment]
I see, it should not crash on an unpatched library.. The patching you do is indeed in the correct location, and I did not know that NOP is not 90 on aarch64 so I learned something today :). After we fix the crash though, you probably also need to look at your patch further, specifically your `this[0x58]` boolean. That has to come out with a value of `true`.

**Comment by biemster** [comment]
Did you already attempt to generate a new python wrapper for the proto file (`protoc soda_api.proto --python_out=.`)? It is actually very possible that that one changed recently.

**Comment by nendonerd** [comment]
generated a new python wrapper for the proto, still same error msg... trying to look into chromium code to see how it calls soda

**Comment by nendonerd** [comment]
So weird, the calling procedure in [speech_recognition_recognizer_impl.cc](https://github.com/chromium/chromium/blob/main/chrome/services/speech/speech_recognition_recognizer_impl.cc#L325) is exactly the same as gasr.py, but when calling `CreateExtendedSodaAsync` it still throws `soda_async_impl.cc:612] Nice value changed from <Unknown> to <Unknown>. Restarting SODA thread.`
Wonder what is `Nice value`

**Comment by nendonerd** [comment]
Can you reproduce the error in linux?

**Comment by biemster** [comment]
I just tested the unpatched lib on linux, and I don't see the crash. It's giving normal output for an unpatched lib..
So I guess this is a MacOS specific issue. Nice value is very likely process priority, but I don't see such messages on linux.
How did you figure out the crash comes from 'CreateExtendedSodaAsync'? Did you run it in gdb? I remember debugging the lib in gdb to fix a crash with some exotic gboard model (although I have to dig to figure out how exactly I did that), so could you provide a stack trace of the crash?

**Comment by biemster** [comment]
Also, 'python3 gasr.py < sample.wav' will not work because the library needs real time microphone input, and not the whole blob at once. There is a flag in the proto that you could set, but I never looked into this further. Could you try with microphone input (although I don't know the command on MacOS since it probably doesn't use ALSA, does ecasound run on your machine)?

**Comment by nendonerd** [comment]
ecasound could not work with mic in MacOS. MacOS does not provide direct access to audio device, u could only access audio from Core Audio API

**Comment by nendonerd** [comment]
maybe i should try making it work on linux or windows first

**Comment by biemster** [comment]
SoX seems to be available: https://stackoverflow.com/questions/40375074/mac-equivalent-of-arecord-command

**Comment by nendonerd** [comment]
does ecasound works on windows?

**Comment by nendonerd** [comment]
will have a try on sox

**Comment by biemster** [comment]
> does ecasound works on windows?

Sorry, I don't allow Windows to enter my house for two decades now so I can't answer that question. (That's probably a bit harsh but I really don't know anything about that, XP was the last version I had to use)

**Comment by nendonerd** [comment]
my windows machine is for gaming only, don't know any thing except steam lol

**Comment by biemster** [comment]
You could set the `simulate_realtime_testonly` flag to true, that should do the trick.
https://github.com/chromium/chromium/blob/main/chrome/services/speech/soda/proto/soda_api.proto#L33

**Comment by nendonerd** [comment]
```
╰─ python gasr.py < sample.wav
WARNING: Logging before InitGoogle() is written to STDERR
W0000 00:00:1653151948.220761   18025 soda_async_impl.cc:334] Creating soda_impl.
W0000 00:00:1653151948.220797   18025 soda_async_impl.cc:336] Created with thread priority 0
W0000 00:00:1653151948.259973   18025 terse_processor.cc:342] TISID disabled.
W0000 00:00:1653151948.265763   18045 portable_intended_query_stream.cc:236] Exiting due to stream cancellation.
W0000 00:00:1653151948.266192   18025 decoder_endpointer_stream.cc:68] Acoustic ep reader thread cancelled.
W0000 00:00:1653151948.266355   18025 soda_async_impl.cc:561] SODA session starting (require_hotword:0, hotword_timeout_in_millis:0, trigger_type:TRIGGER_TYPE_UNSPECIFIED, hybrid_asr_config.mode:MODE_DEFAULT)
W0000 00:00:1653151948.286475   18026 soda_async_impl.cc:1327] SODA received first mic audio buffer, size in bytes: 640, format: 1, channels: 1, : sample rate: 16000
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 237, in 'calling callback function'
  File "gasr.py", line 47, in resultHandler
    if res.soda_type == SodaResponse.SodaMessageType.RECOGNITION:
AttributeError: 'EnumTypeWrapper' object has no attribute 'RECOGNITION'
```
just patched linux soda with a bunch of 90s, and add the flag, but get some error... 
`print(res.soda_type)` shows lots of 6 , which is `AUDIO_LEVEL`, and some 5, which is `ENDPOINT`

**Comment by nendonerd** [comment]
modify `if res.soda_type == SodaResponse.SodaMessageType.RECOGNITION:` to `if res.soda_type == SodaResponse.RECOGNITION:` fixed the error

**Comment by biemster** [comment]
I've seen this and fixed it a while ago, maybe I did not commit it. Let me check (but first sleep, sorry..)

**Comment by biemster** [comment]
So you got it working?

**Comment by nendonerd** [comment]
i think gasr should be working, but still struggling to make ecasound work in wsl...

**Comment by jr-k** [comment]
A new version 1.1.1.2 is available, maybe it's worth the try.

**Comment by janboeye** [comment]
@nendonerd macos report Code signature invalid, do you know how to work around this? Thanks
