### ISSUE TITLE
Session gets cancelled even after patching libsoda.so

### ISSUE THREAD

**Issue by RYSKZ** [biemster/gasr#13]
Hello!

First of all, thank you very much for all your work. I have been following this project for a long time but just found the time to patch the libsoda.so file in order to be usable. I have followed the advice provided in other issues but am struggling to get this to work.

I have initialized the variable that holds the results of the four checks to true instead of false.
![image](https://user-images.githubusercontent.com/25695666/185604870-2d8414db-44c3-4697-8d96-a9da8569d224.png)

I have replaced the call to the first of those checks for an unconditional jump that skips all the four checks.
![image](https://user-images.githubusercontent.com/25695666/185604881-8e846c53-2bcd-4248-9e7f-315922ea1a21.png)

I tried to transcribe a pre-recorded WAV file with the correct format (PCM, s16le) inside WSL. It works for the first chunk of audio but the session gets cancelled afterwards.
![image](https://user-images.githubusercontent.com/25695666/185604886-65689679-eb68-4c9d-9c5f-eaee85c9cb36.png)

I have tried many variations (e.g., NOPing the four checks instead of skipping them) but I always get the same result :(

I have noticed that there is a SHA1 hash calculation of the first parameter (which I guess that is the ExtendedSodaConfigMsg) before the four checks and that the result is used in a later part of the same function. This configuration contains, among other things the SODA API Key which in my case is a dummy API Key since I were unable to dump it from Google Chrome. Is this related to the session cancellation or does the error come from somewhere else?

I would be very grateful for some guidance.

**Comment by anasalmahmud** [comment]
have you try to generate a new python wrapper for the proto file?
you can generate using this command `protoc soda_api.proto --python_out=.`
( copy the proto file from [here](https://source.chromium.org/chromium/chromium/src/+/main:chrome/services/speech/soda/proto/soda_api.proto) )
and also try to add `cfg_proto.simulate_realtime_testonly = True` to `class SodaClient()` in `gasr.py
`

**Comment by RYSKZ** [comment]
Thank you very much for yout help! I followed your steps and now it works perfectly for both transcription of a WAV file and real-time transcription of the audio recorded from the microphone.

Thank you very much again :)

**Comment by anasalmahmud** [comment]
My Pleasure, I need some information. please check your email
