### ISSUE TITLE
Where can i find french model or other languages？

### ISSUE THREAD

**Issue by goddade** [biemster/gasr#14]

**Comment by biemster** [comment]
The file [constants.h](https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/components/soda/constants.h) in the chromium source contains the crx ids of the language packs, which you can convert to ascii using this bit of python:
```python
h = [0x6e, 0x0e, ... rest of the fr-FR hex]
crxid = ''
for c in h[:32]:
    crxid += chr(c + ord('a'))
print(crxid)
```
This id is what you need to download the crx3 extension using a tool like https://robwu.nl/crxviewer/

**Comment by goddade** [comment]
> The file [constants.h](https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/components/soda/constants.h) in the chromium source contains the crx ids of the language packs, which you can convert to ascii using this bit of python:
> 
> ```python
> h = [0x6e, 0x0e, ... rest of the fr-FR hex]
> crxid = ''
> for c in h[:32]:
>     crxid += chr(c + ord('a'))
> print(crxid)
> ```
> 
> This id is what you need to download the crx3 extension using a tool like https://robwu.nl/crxviewer/

Thank you!

**Comment by goddade** [comment]
I get a non-ascii string:
ÏoĴħņ|¿śŐ£ ¸Ět·¨¹ļ×êÒŌŎ©ÍčĶā

**Comment by biemster** [comment]
hm yeah I forgot, the hex characters have to be single, so instead of `h = [0x6e, 0x0e, ...]` what I wrote earlier, it should be `h = [0x6, 0xe, 0x0, 0xe, ...]`

**Comment by goddade** [comment]
```
...
for c in h[:16]:
    crxid += chr(((c>>4)&0x0f) +ord('a'))
    crxid += chr((c&0x0f) +ord('a'))
...
```

**Comment by biemster** [comment]
or that :smile:

**Comment by dlxj** [comment]
Could anyone tell me if it's still possible to download the language model using this method? I tried, but it showed a 404 error and couldn't be downloaded.

**Comment by biemster** [comment]
This method should still work. Also, I'm almost finished with the chromeos version of SODA after which all the models mentioned here can be used: https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/components/soda/soda_installer_impl_chromeos.cc

Those are available on simpler links like https://edgedl.me.gvt1.com/edgedl/dlc/hatch-release/R128-15955.0.0/dlc-scaled/libsoda-model-fr-fr-cnch24d1/package/dlc.img

**Comment by goddade** [comment]
Select the language in chrome, and then the model is in ~/.config/google-chrome/SODALanguages/

**Comment by goddade** [comment]
> Select the language in chrome, and then the model is in ~/.config/google-chrome/SODALanguages/

chrome://settings/captions, Add languages
