### ISSUE TITLE
Could anyone share the language model?

### ISSUE THREAD

**Issue by dlxj** [biemster/gasr#21]
Could anyone please share the language model that works correctly with this project? The old version of the language model is no longer available for download, thanks in advance.

**Comment by biemster** [comment]
I'm almost finished with the chromeos version of SODA after which all the models mentioned here can be used: https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/components/soda/soda_installer_impl_chromeos.cc

Those are available on simpler links like https://edgedl.me.gvt1.com/edgedl/dlc/hatch-release/R128-15955.0.0/dlc-scaled/libsoda-model-fr-fr-cnch24d1/package/dlc.img

I'm currently reworking this project to move both the library and models to the chromeos version of soda, including a downloader and patcher.

**Comment by biemster** [comment]
and arm64 (rpi)!

**Comment by kocsaga** [comment]
Well, that would be awesome. I am looking forward for it. All other alternatives not as precise as googles solution. I tried this repo, but can't make it work. Maybe my skills is not enough or maybe the method changed a lot.

**Comment by goddade** [comment]
> I'm almost finished with the chromeos version of SODA after which all the models mentioned here can be used: https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/components/soda/soda_installer_impl_chromeos.cc
> 
> Those are available on simpler links like https://edgedl.me.gvt1.com/edgedl/dlc/hatch-release/R128-15955.0.0/dlc-scaled/libsoda-model-fr-fr-cnch24d1/package/dlc.img
> 
> I'm currently reworking this project to move both the library and models to the chromeos version of soda, including a downloader and patcher.

What is the difference between chrome version and os version? Chrome OS has arm so.

**Comment by cepsong** [comment]
Do we have the solution yet since this issue is closed as completed? I cannot find it anywhere. @dlxj @biemster Thanks a lot in advance.

**Comment by biemster** [comment]
I'll update the code when I get to it, but in the mean time following what's written in the other closed issue you commented on should suffice.
