### ISSUE TITLE
ChromeOS SODA & models links?

### ISSUE THREAD

**Issue by 0xEb0** [biemster/gasr#22]
Hi,

Thank you for sharing your progress! I’m really curious about the ChromeOS version of SODA and the links you provided for downloading models (e.g., https://edgedl.me.gvt1.com/edgedl/dlc/...). Could you kindly explain how you obtained those links? Any tips or pointers would be greatly appreciated.

Thanks again, and great work on this project!

**Comment by biemster** [comment]
I honestly do not fully remember how I found the first link, but I think that the DLC utility in chromeos writes it in a log somewhere? Or maybe I used mitmproxy? But I think it's just in the log on the chromebook (I don't have than machine running now..) There should be something called `dlc_utils` or something in the terminal you can play around with.

https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/dlcservice

Then I followed the advice in the `brunch` repo (https://github.com/sebanc/brunch?tab=readme-ov-file#intel) to find which platform matches the cpu architecture of where you want to run `gasr`, which basically takes a lot of searching on https://cros.tech/device. Once you find a device with a similar enough CPU you can select which version and subversion of ChromeOS you want, and use those numbers in the link.

I hope this is a bit clear story (it's been a while), feel free to ask further if necessary.

**Comment by biemster** [comment]
I will continue working on this once I have my postmarketOS phone on a daily driver level (which is currently my main reason to develop this)

**Comment by biemster** [comment]
Yes it's definitely in the DLC logs on the chromebook, I remember jumping through hoops to copy paste it to my work machine :)

**Comment by cepsong** [comment]
@biemster is this solution ready? waiting to test out the latest soda model but currently cannot compile it successfully on windows.

**Comment by biemster** [comment]
The solution is not ready to push here, but following what is written above should definitely be doable. The C code is only left for reference and very likely does not compile anywhere anymore, the python script is what is maintained.

**Comment by biemster** [comment]
I just noticed that I forgot about the `DT_RELR without GLIBC_ABI_DT_RELR dependency` issue with the ChromeOS libraries. This is something about relocation tables in the library, and the libc on the host has to be able to deal with it. I remember patching `/lib/ld-linux-armhf.so.3` on my rpi4 for this succesfully, but after updating the system today I actually made it unbootable. Once this is figured out fully I can update the repository with this new approach.

**Comment by biemster** [comment]
yes autopatch I am considering too. The ChromeOS library however requires patching the hosts ld-linux library too, which can result in a bricked OS (which I did yesterday) and will need to be redone after every system update, so it will have to come with significant warnings
