### ISSUE TITLE
Code not running on Mac

### ISSUE THREAD

**Issue by nome2050** [biemster/gasr#4]
`python gasr.py
W0326 17:32:01.784220       1 soda_async_impl.cc:260] Creating soda_impl
W0326 17:32:01.923203       1 terse_processor.cc:1704] SODA could not build Hotquery Matcher.
W0326 17:32:01.923333       1 terse_processor.cc:279] TISID disabled.
W0326 17:32:01.932739       2 incremental_result.cc:218] UNKNOWN: Result lattice is not set. [type.googleapis.com/util.ErrorSpacePayload='SpeechErrorSpace::SpeechError(-73542)']
W0326 17:32:01.936932       1 soda_async_impl.cc:419] Soda session starting (require_hotword:0, hotword_timeout_in_millis:0, trigger_type:TRIGGER_TYPE_UNSPECIFIED, hybrid_asr_config.mode:MODE_DEFAULT)
[1]    26539 segmentation fault  python `

**Comment by biemster** [comment]
I don't have a Mac to test on (or a Windows box), so I can only provide support for Linux issues, sorry.

**Comment by biemster** [comment]
Although this could be anything, since it has very little info. Since it did not even read the language model, did you correctly point to the language model directory?

**Comment by nome2050** [comment]
![Screenshot 2021-03-26 at 6 08 03 PM](https://user-images.githubusercontent.com/41596125/112635968-49bb1700-8e5e-11eb-8ab4-d68ecbfc9bc3.png)

**Comment by nome2050** [comment]
i did put the SODAModels and libdosa.so in my directory

**Comment by biemster** [comment]
I never ran this on macos, does the C code do anything?

**Comment by nome2050** [comment]
I haven't tried running this on C ... 
but i did try running with ecasound , that gives error
![Screenshot 2021-03-26 at 6 16 52 PM](https://user-images.githubusercontent.com/41596125/112636949-80456180-8e5f-11eb-86ad-28861c68e9d4.png)

**Comment by biemster** [comment]
that's a jackd error, not related to this project. Try with file input maybe?

**Comment by nome2050** [comment]
![Screenshot 2021-03-26 at 6 22 39 PM](https://user-images.githubusercontent.com/41596125/112637741-4a54ad00-8e60-11eb-9dcf-d8973c23821c.png)

Tried that too .... this is the wav file that u posted on another issue

**Comment by biemster** [comment]
`./gasr --stream-delay < samples_cpp_windows_console_samples_whatstheweatherlike.wav`

**Comment by nome2050** [comment]
./gasr --stream-delay < samples_cpp_windows_console_samples_whatstheweatherlike.wav
dyld: Library not loaded: blaze-out/darwin_x86_64-opt/bin/speech/soda/chrome/libsoda_chrome.so
  Referenced from: ./gasr
  Reason: image not found
[1]    28437 abort      ./gasr --stream-delay <

**Comment by biemster** [comment]
Thats odd, it requires an extra library I did not see before. What does `ldd libsoda.so` return?

**Comment by nome2050** [comment]
otool -L libsoda.so 

libsoda.so:
	blaze-out/darwin_x86_64-opt/bin/speech/soda/chrome/libsoda_chrome.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1770.255.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1770.255.0)

**Comment by biemster** [comment]
This really seems to be a macos specific issue (although maybe it will show up on linux soon too), and since I don't have this hardware you're pretty much on your own here... (or sponsor me a mac mini? jk) Sorry

**Comment by nome2050** [comment]
alright let me try on linux ... and i will see how it goes.. thanks for the help

**Comment by jacobweber** [comment]
@nome2050 I was able to get past that "image not found" error by actually copying libsoda.so to that path: `blaze-out/darwin_x86_64-opt/bin/speech/soda/chrome/libsoda_chrome.so`, relative to the gasr directory.

Couldn't really get it to work after that, though. I'd be interested to know if you do.

**Comment by biemster** [comment]
@jacobweber what issue did you run into after that?

**Comment by jacobweber** [comment]
@biemster With the caveat that I don't really know what I'm doing, and didn't figure out that API key stuff, I got this, but no text in the output:

```
$ sox "test.wav" -ts16 - | ./gasr --stream-delay
W0326 13:29:30.028538       1 soda_async_impl.cc:260] Creating soda_impl
W0326 13:29:32.862323       1 terse_processor.cc:1704] SODA could not build Hotquery Matcher.
W0326 13:29:32.862519       1 terse_processor.cc:279] TISID disabled.
W0326 13:29:32.914503       2 portable_intended_query_stream.cc:235] Exiting due to stream cancellation.
W0326 13:29:32.915876       1 decoder_endpointer_stream.cc:40] Acoustic ep reader thread cancelled.
W0326 13:29:32.917239       1 soda_async_impl.cc:419] Soda session starting (require_hotword:0, hotword_timeout_in_millis:0, trigger_type:TRIGGER_TYPE_UNSPECIFIED, hybrid_asr_config.mode:MODE_DEFAULT)
W0326 13:29:32.918384       2 soda_async_impl.cc:1082] SODA received first mic audio buffer, size in bytes: 640, format: 1, channels: 1, : sample rate: 16000
W0326 13:29:32.927592       2 lag_detector.cc:30] Pipeline lagging by 2899 ms. Continue processing samples.
...
W0326 13:29:33.433001       2 soda_async_impl.cc:852] Not receiving any loopback audio in 500ms. Last audio received time: 0, Current time in us: 1616790573433001
W0326 13:29:33.500611       2 lag_detector.cc:30] Pipeline lagging by 2672 ms. Continue processing samples.
...
W0326 13:30:29.009684       2 soda_async_impl.cc:759] SODA stopped processing audio, mics audio processed in millis: 77400, loopback audio processed in millis: 0
W0326 13:30:29.010313       3 portable_intended_query_stream.cc:235] Exiting due to stream cancellation.
W0326 13:30:29.010916       2 decoder_endpointer_stream.cc:40] Acoustic ep reader thread cancelled.
W0326 13:30:29.011495       2 soda_async_impl.cc:809] Soda session stopped due to: STOP_CALLED
W0326 13:30:29.049979       1 soda_async_impl.cc:880] Deleting soda_impl
```

**Comment by biemster** [comment]
SoX indeed introduces lag internally, but the library can handle a bit of it. The rest of the output looks good, so it seems your workaround is a solid one :+1: . When you figure out the API key stuff and the call stack verification, you should have a working setup on your mac!

**Comment by ulysso** [comment]
Ohh funny timing, I also just started trying it today, on MacOS too.  The C version worked right away, for Extended Soda in Python to work I had to cast the `CreateExtendedSodaAsync` returned handle to `ctypes.c_void_p` explicitly otherwise it would segfault for me, just in case it helps anyone here.

Awesome project, thanks for all the work @biemster!

**Comment by jacobweber** [comment]
I got it working! First time I've ever disassembled or patched a binary, so I'm feeling pretty proud of myself. 😀

**Comment by jacobweber** [comment]
@ulysso Can you share what you did exactly? I tried inserting `self.handle = ctypes.cast(self.handle, ctypes.c_void_p)` at line 35, but still got `Segmentation Fault: 11` on the next line.

**Comment by ulysso** [comment]
@jacobweber 

for init
```
self.sodalib = ctypes.CDLL('./libsoda.so')
self.sodalib.CreateExtendedSodaAsync.restype = ctypes.c_void_p
```

and start:
```self.handle = ctypes.c_void_p(self.sodalib.CreateExtendedSodaAsync(self.config))```

**Comment by jacobweber** [comment]
@ulysso Thanks!

**Comment by nome2050** [comment]
How can i give an audio file to python code...because I did what ulysso said and the code has started running but gives no output
![Screenshot 2021-03-29 at 3 46 02 PM](https://user-images.githubusercontent.com/41596125/112826017-e02d4980-90a5-11eb-8c3d-9b7c0873b597.png)

no output after this...does this have anything to do with the API dummy key....because I just cloned the repo and kept in libdosa.so and sodaModels... I did nothing else...kindly help me out

**Comment by biemster** [comment]
Did you patch your libsoda? If not yet, please follow the pointers on the project page. You'll need to disassemble the library, and change the binary so the checks pass. (There are plenty of tutorials and CTF instructions that will help you out with this.)

**Comment by jacobweber** [comment]
@nome2050 But when you do, just pipe the audio into the python script, e.g. `./gasr.py < your-mono-16k-audio.wav`.

I haven't gotten it working yet with the [latest commit](https://github.com/biemster/gasr/commit/df3a49ebe4a09c3bf971caef18b88fdaf4fc09cb), but it's working without that.

**Comment by biemster** [comment]
@jacobweber To work with the protobufs implemented in the latest commit, you need to patch the CreateExtendedSodaAsync function as well. Maybe that's why it's not working for you yet?

**Comment by jacobweber** [comment]
Oh, good point.

**Comment by jacobweber** [comment]
Yep, works after patching that. And for whatever reason, the extended version seems to work a lot better (the older Python version and the C version were not "finalizing" a lot of stuff).

**Comment by biemster** [comment]
This seems to have been worked out, thanks @ulysso and @jacobweber for the fixes!
